
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BuffDef : Luban.BeanBase
{
    public BuffDef(JSONNode _buf) 
    {
        { if(!_buf["BuffId"].IsNumber) { throw new SerializationException(); }  BuffId = _buf["BuffId"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Category"].IsNumber) { throw new SerializationException(); }  Category = (BuffCategory)_buf["Category"].AsInt; }
        { if(!_buf["Duration"].IsNumber) { throw new SerializationException(); }  Duration = _buf["Duration"]; }
        { if(!_buf["TickInterval"].IsNumber) { throw new SerializationException(); }  TickInterval = _buf["TickInterval"]; }
        { if(!_buf["TickDamage"].IsNumber) { throw new SerializationException(); }  TickDamage = _buf["TickDamage"]; }
        { if(!_buf["Param0"].IsNumber) { throw new SerializationException(); }  Param0 = _buf["Param0"]; }
    }

    public static BuffDef DeserializeBuffDef(JSONNode _buf)
    {
        return new BuffDef(_buf);
    }

    /// <summary>
    /// BuffID
    /// </summary>
    public readonly int BuffId;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 类别
    /// </summary>
    public readonly BuffCategory Category;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// DOT间隔
    /// </summary>
    public readonly float TickInterval;
    /// <summary>
    /// DOT伤害
    /// </summary>
    public readonly int TickDamage;
    /// <summary>
    /// 参数0
    /// </summary>
    public readonly float Param0;
   
    public const int __ID__ = 1892617874;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BuffId:" + BuffId + ","
        + "Name:" + Name + ","
        + "Category:" + Category + ","
        + "Duration:" + Duration + ","
        + "TickInterval:" + TickInterval + ","
        + "TickDamage:" + TickDamage + ","
        + "Param0:" + Param0 + ","
        + "}";
    }
}
}

