
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BuffCategory
    {
        None = 0,
        Dot = 1,
        Slow = 2,
        Stun = 3,
        DamageAmp = 4,
    }

} 

