
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BulletDef : Luban.BeanBase
{
    public BulletDef(JSONNode _buf) 
    {
        { if(!_buf["BulletId"].IsNumber) { throw new SerializationException(); }  BulletId = _buf["BulletId"]; }
        { if(!_buf["TowerId"].IsNumber) { throw new SerializationException(); }  TowerId = _buf["TowerId"]; }
        { if(!_buf["Level"].IsNumber) { throw new SerializationException(); }  Level = _buf["Level"]; }
        { if(!_buf["Damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["Damage"]; }
        { if(!_buf["MoveSpeed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _buf["MoveSpeed"]; }
        { if(!_buf["BodyRadius"].IsNumber) { throw new SerializationException(); }  BodyRadius = _buf["BodyRadius"]; }
        { if(!_buf["Scale"].IsNumber) { throw new SerializationException(); }  Scale = _buf["Scale"]; }
        { if(!_buf["Speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["Speed"]; }
        { if(!_buf["IsRemove"].IsNumber) { throw new SerializationException(); }  IsRemove = _buf["IsRemove"]; }
        { if(!_buf["OnHitBuffId"].IsNumber) { throw new SerializationException(); }  OnHitBuffId = _buf["OnHitBuffId"]; }
    }

    public static BulletDef DeserializeBulletDef(JSONNode _buf)
    {
        return new BulletDef(_buf);
    }

    /// <summary>
    /// 子弹ID
    /// </summary>
    public readonly int BulletId;
    /// <summary>
    /// 塔ID
    /// </summary>
    public readonly int TowerId;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 飞行速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 碰撞半径
    /// </summary>
    public readonly float BodyRadius;
    /// <summary>
    /// 缩放
    /// </summary>
    public readonly float Scale;
    /// <summary>
    /// speed
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 穿透
    /// </summary>
    public readonly int IsRemove;
    /// <summary>
    /// 命中Buff
    /// </summary>
    public readonly int OnHitBuffId;
   
    public const int __ID__ = -1027633277;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BulletId:" + BulletId + ","
        + "TowerId:" + TowerId + ","
        + "Level:" + Level + ","
        + "Damage:" + Damage + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "BodyRadius:" + BodyRadius + ","
        + "Scale:" + Scale + ","
        + "Speed:" + Speed + ","
        + "IsRemove:" + IsRemove + ","
        + "OnHitBuffId:" + OnHitBuffId + ","
        + "}";
    }
}
}

