
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BulletMoveType
    {
        /// <summary>
        /// 默认/未配置
        /// </summary>
        None = 0,
        /// <summary>
        /// 追踪弹
        /// </summary>
        Homing = 1,
        /// <summary>
        /// 直线弹
        /// </summary>
        Straight = 2,
    }

} 

