
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ItemDef : Luban.BeanBase
{
    public ItemDef(JSONNode _buf) 
    {
        { if(!_buf["ItemTypeId"].IsNumber) { throw new SerializationException(); }  ItemTypeId = _buf["ItemTypeId"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Live"].IsNumber) { throw new SerializationException(); }  Live = _buf["Live"]; }
        { if(!_buf["Money"].IsNumber) { throw new SerializationException(); }  Money = _buf["Money"]; }
        { if(!_buf["BodyRadius"].IsNumber) { throw new SerializationException(); }  BodyRadius = _buf["BodyRadius"]; }
        { if(!_buf["Scale"].IsNumber) { throw new SerializationException(); }  Scale = _buf["Scale"]; }
        { if(!_buf["FaceDirection"].IsNumber) { throw new SerializationException(); }  FaceDirection = _buf["FaceDirection"]; }
        { if(!_buf["OffsetX"].IsNumber) { throw new SerializationException(); }  OffsetX = _buf["OffsetX"]; }
        { if(!_buf["OffsetY"].IsNumber) { throw new SerializationException(); }  OffsetY = _buf["OffsetY"]; }
    }

    public static ItemDef DeserializeItemDef(JSONNode _buf)
    {
        return new ItemDef(_buf);
    }

    /// <summary>
    /// 道具类型ID
    /// </summary>
    public readonly int ItemTypeId;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 耐久
    /// </summary>
    public readonly int Live;
    /// <summary>
    /// 金币
    /// </summary>
    public readonly int Money;
    /// <summary>
    /// 碰撞半径
    /// </summary>
    public readonly float BodyRadius;
    /// <summary>
    /// 缩放
    /// </summary>
    public readonly float Scale;
    /// <summary>
    /// 朝向
    /// </summary>
    public readonly float FaceDirection;
    /// <summary>
    /// X偏移
    /// </summary>
    public readonly float OffsetX;
    /// <summary>
    /// Y偏移
    /// </summary>
    public readonly float OffsetY;
   
    public const int __ID__ = -514135086;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemTypeId:" + ItemTypeId + ","
        + "Name:" + Name + ","
        + "Live:" + Live + ","
        + "Money:" + Money + ","
        + "BodyRadius:" + BodyRadius + ","
        + "Scale:" + Scale + ","
        + "FaceDirection:" + FaceDirection + ","
        + "OffsetX:" + OffsetX + ","
        + "OffsetY:" + OffsetY + ","
        + "}";
    }
}
}

