
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class MonsterDef : Luban.BeanBase
{
    public MonsterDef(JSONNode _buf) 
    {
        { if(!_buf["MonsterId"].IsNumber) { throw new SerializationException(); }  MonsterId = _buf["MonsterId"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["Hp"]; }
        { if(!_buf["Scale"].IsNumber) { throw new SerializationException(); }  Scale = _buf["Scale"]; }
        { if(!_buf["FaceDirection"].IsNumber) { throw new SerializationException(); }  FaceDirection = _buf["FaceDirection"]; }
        { if(!_buf["OffsetX"].IsNumber) { throw new SerializationException(); }  OffsetX = _buf["OffsetX"]; }
        { if(!_buf["OffsetY"].IsNumber) { throw new SerializationException(); }  OffsetY = _buf["OffsetY"]; }
    }

    public static MonsterDef DeserializeMonsterDef(JSONNode _buf)
    {
        return new MonsterDef(_buf);
    }

    /// <summary>
    /// 怪物ID
    /// </summary>
    public readonly int MonsterId;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 大小
    /// </summary>
    public readonly float Scale;
    /// <summary>
    /// 初始朝向
    /// </summary>
    public readonly float FaceDirection;
    /// <summary>
    /// X轴偏移
    /// </summary>
    public readonly float OffsetX;
    /// <summary>
    /// Y轴偏移
    /// </summary>
    public readonly float OffsetY;
   
    public const int __ID__ = -173581845;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "MonsterId:" + MonsterId + ","
        + "Name:" + Name + ","
        + "Hp:" + Hp + ","
        + "Scale:" + Scale + ","
        + "FaceDirection:" + FaceDirection + ","
        + "OffsetX:" + OffsetX + ","
        + "OffsetY:" + OffsetY + ","
        + "}";
    }
}
}

