
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 肉鸽局外/开战效果类型
    /// </summary>
    public enum RoguelikeEffectType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// Param0=数量
        /// </summary>
        StartCoin = 1,
        /// <summary>
        /// Param0=百分点数
        /// </summary>
        TowerDamagePercent = 2,
        /// <summary>
        /// Param0=TbBuffId
        /// </summary>
        GrantGlobalBuff = 3,
        /// <summary>
        /// Param0=数量
        /// </summary>
        StartingRoguelikeGold = 4,
    }

} 

