
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RoguelikeItemDef : Luban.BeanBase
{
    public RoguelikeItemDef(JSONNode _buf) 
    {
        { if(!_buf["ItemId"].IsNumber) { throw new SerializationException(); }  ItemId = _buf["ItemId"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
        { if(!_buf["MaxOwn"].IsNumber) { throw new SerializationException(); }  MaxOwn = _buf["MaxOwn"]; }
        { var __json0 = _buf["EffectIds"]; if(!__json0.IsArray) { throw new SerializationException(); } EffectIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  EffectIds.Add(__v0); }   }
    }

    public static RoguelikeItemDef DeserializeRoguelikeItemDef(JSONNode _buf)
    {
        return new RoguelikeItemDef(_buf);
    }

    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 持有上限
    /// </summary>
    public readonly int MaxOwn;
    /// <summary>
    /// 效果ID列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> EffectIds;
   
    public const int __ID__ = -92844447;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemId:" + ItemId + ","
        + "Name:" + Name + ","
        + "Price:" + Price + ","
        + "MaxOwn:" + MaxOwn + ","
        + "EffectIds:" + Luban.StringUtil.CollectionToString(EffectIds) + ","
        + "}";
    }
}
}

