
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RoguelikeEffectDef : Luban.BeanBase
{
    public RoguelikeEffectDef(JSONNode _buf) 
    {
        { if(!_buf["EffectId"].IsNumber) { throw new SerializationException(); }  EffectId = _buf["EffectId"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = (RoguelikeEffectType)_buf["Type"].AsInt; }
        { if(!_buf["Param0"].IsNumber) { throw new SerializationException(); }  Param0 = _buf["Param0"]; }
    }

    public static RoguelikeEffectDef DeserializeRoguelikeEffectDef(JSONNode _buf)
    {
        return new RoguelikeEffectDef(_buf);
    }

    /// <summary>
    /// 效果ID
    /// </summary>
    public readonly int EffectId;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly RoguelikeEffectType Type;
    /// <summary>
    /// 参数0
    /// </summary>
    public readonly int Param0;
   
    public const int __ID__ = 1668659043;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "EffectId:" + EffectId + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "Param0:" + Param0 + ","
        + "}";
    }
}
}

