
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RoguelikeLevelDef : Luban.BeanBase
{
    public RoguelikeLevelDef(JSONNode _buf) 
    {
        { if(!_buf["BigLevelId"].IsNumber) { throw new SerializationException(); }  BigLevelId = _buf["BigLevelId"]; }
        { if(!_buf["LevelId"].IsNumber) { throw new SerializationException(); }  LevelId = _buf["LevelId"]; }
        { if(!_buf["DisplayName"].IsString) { throw new SerializationException(); }  DisplayName = _buf["DisplayName"]; }
        { if(!_buf["HexMapAssetId"].IsString) { throw new SerializationException(); }  HexMapAssetId = _buf["HexMapAssetId"]; }
        { if(!_buf["ShopPoolId"].IsNumber) { throw new SerializationException(); }  ShopPoolId = _buf["ShopPoolId"]; }
        { if(!_buf["StartingGold"].IsNumber) { throw new SerializationException(); }  StartingGold = _buf["StartingGold"]; }
        { var __json0 = _buf["StartingEffectIds"]; if(!__json0.IsArray) { throw new SerializationException(); } StartingEffectIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  StartingEffectIds.Add(__v0); }   }
        { if(!_buf["EncounterTableId"].IsNumber) { throw new SerializationException(); }  EncounterTableId = _buf["EncounterTableId"]; }
        { if(!_buf["RandomEventPoolId"].IsNumber) { throw new SerializationException(); }  RandomEventPoolId = _buf["RandomEventPoolId"]; }
    }

    public static RoguelikeLevelDef DeserializeRoguelikeLevelDef(JSONNode _buf)
    {
        return new RoguelikeLevelDef(_buf);
    }

    /// <summary>
    /// 大关
    /// </summary>
    public readonly int BigLevelId;
    /// <summary>
    /// 小关
    /// </summary>
    public readonly int LevelId;
    /// <summary>
    /// 显示名
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// Hex地图资源名
    /// </summary>
    public readonly string HexMapAssetId;
    /// <summary>
    /// 商店池
    /// </summary>
    public readonly int ShopPoolId;
    /// <summary>
    /// 开局肉鸽金
    /// </summary>
    public readonly int StartingGold;
    /// <summary>
    /// 开局效果ID列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> StartingEffectIds;
    /// <summary>
    /// 遭遇表
    /// </summary>
    public readonly int EncounterTableId;
    /// <summary>
    /// 随机事件池
    /// </summary>
    public readonly int RandomEventPoolId;
   
    public const int __ID__ = -1891900078;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BigLevelId:" + BigLevelId + ","
        + "LevelId:" + LevelId + ","
        + "DisplayName:" + DisplayName + ","
        + "HexMapAssetId:" + HexMapAssetId + ","
        + "ShopPoolId:" + ShopPoolId + ","
        + "StartingGold:" + StartingGold + ","
        + "StartingEffectIds:" + Luban.StringUtil.CollectionToString(StartingEffectIds) + ","
        + "EncounterTableId:" + EncounterTableId + ","
        + "RandomEventPoolId:" + RandomEventPoolId + ","
        + "}";
    }
}
}

