
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RoguelikeShopPoolDef : Luban.BeanBase
{
    public RoguelikeShopPoolDef(JSONNode _buf) 
    {
        { if(!_buf["PoolId"].IsNumber) { throw new SerializationException(); }  PoolId = _buf["PoolId"]; }
        { if(!_buf["PickCount"].IsNumber) { throw new SerializationException(); }  PickCount = _buf["PickCount"]; }
        { var __json0 = _buf["ItemIds"]; if(!__json0.IsArray) { throw new SerializationException(); } ItemIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ItemIds.Add(__v0); }   }
        { var __json0 = _buf["Weights"]; if(!__json0.IsArray) { throw new SerializationException(); } Weights = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Weights.Add(__v0); }   }
    }

    public static RoguelikeShopPoolDef DeserializeRoguelikeShopPoolDef(JSONNode _buf)
    {
        return new RoguelikeShopPoolDef(_buf);
    }

    /// <summary>
    /// 货架池ID
    /// </summary>
    public readonly int PoolId;
    /// <summary>
    /// 抽取数量(&lt;=0全取)
    /// </summary>
    public readonly int PickCount;
    /// <summary>
    /// 道具ID列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> ItemIds;
    /// <summary>
    /// 权重列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> Weights;
   
    public const int __ID__ = 600896866;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "PoolId:" + PoolId + ","
        + "PickCount:" + PickCount + ","
        + "ItemIds:" + Luban.StringUtil.CollectionToString(ItemIds) + ","
        + "Weights:" + Luban.StringUtil.CollectionToString(Weights) + ","
        + "}";
    }
}
}

