
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbMonster TbMonster {get; }
    public TbTower TbTower {get; }
    public TbBullet TbBullet {get; }
    public TbBuff TbBuff {get; }
    public TbItem TbItem {get; }
    /// <summary>
    /// 肉鸽效果
    /// </summary>
    public TbRoguelikeEffect TbRoguelikeEffect {get; }
    /// <summary>
    /// 肉鸽商店道具
    /// </summary>
    public TbRoguelikeItem TbRoguelikeItem {get; }
    /// <summary>
    /// 肉鸽商店池
    /// </summary>
    public TbRoguelikeShopPool TbRoguelikeShopPool {get; }
    /// <summary>
    /// 肉鸽小关
    /// </summary>
    public TbRoguelikeLevel TbRoguelikeLevel {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbMonster = new TbMonster(loader("tbmonster"));
        TbTower = new TbTower(loader("tbtower"));
        TbBullet = new TbBullet(loader("tbbullet"));
        TbBuff = new TbBuff(loader("tbbuff"));
        TbItem = new TbItem(loader("tbitem"));
        TbRoguelikeEffect = new TbRoguelikeEffect(loader("tbroguelikeeffect"));
        TbRoguelikeItem = new TbRoguelikeItem(loader("tbroguelikeitem"));
        TbRoguelikeShopPool = new TbRoguelikeShopPool(loader("tbroguelikeshoppool"));
        TbRoguelikeLevel = new TbRoguelikeLevel(loader("tbroguelikelevel"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbMonster.ResolveRef(this);
        TbTower.ResolveRef(this);
        TbBullet.ResolveRef(this);
        TbBuff.ResolveRef(this);
        TbItem.ResolveRef(this);
        TbRoguelikeEffect.ResolveRef(this);
        TbRoguelikeItem.ResolveRef(this);
        TbRoguelikeShopPool.ResolveRef(this);
        TbRoguelikeLevel.ResolveRef(this);
    }
}

}
