
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbMonster TbMonster {get; }
    public TbTower TbTower {get; }
    public TbBullet TbBullet {get; }
    public TbBuff TbBuff {get; }
    public TbItem TbItem {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbMonster = new TbMonster(loader("tbmonster"));
        TbTower = new TbTower(loader("tbtower"));
        TbBullet = new TbBullet(loader("tbbullet"));
        TbBuff = new TbBuff(loader("tbbuff"));
        TbItem = new TbItem(loader("tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbMonster.ResolveRef(this);
        TbTower.ResolveRef(this);
        TbBullet.ResolveRef(this);
        TbBuff.ResolveRef(this);
        TbItem.ResolveRef(this);
    }
}

}
