
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBullet
{
    private readonly System.Collections.Generic.Dictionary<int, BulletDef> _dataMap;
    private readonly System.Collections.Generic.List<BulletDef> _dataList;
    
    public TbBullet(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, BulletDef>(count);
        _dataList = new System.Collections.Generic.List<BulletDef>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BulletDef _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.BulletDef.DeserializeBulletDef(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.BulletId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BulletDef> DataMap => _dataMap;
    public System.Collections.Generic.List<BulletDef> DataList => _dataList;

    public BulletDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BulletDef Get(int key) => _dataMap[key];
    public BulletDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

