
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBuff
{
    private readonly System.Collections.Generic.Dictionary<int, BuffDef> _dataMap;
    private readonly System.Collections.Generic.List<BuffDef> _dataList;
    
    public TbBuff(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, BuffDef>(count);
        _dataList = new System.Collections.Generic.List<BuffDef>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BuffDef _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.BuffDef.DeserializeBuffDef(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.BuffId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BuffDef> DataMap => _dataMap;
    public System.Collections.Generic.List<BuffDef> DataList => _dataList;

    public BuffDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BuffDef Get(int key) => _dataMap[key];
    public BuffDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

