
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbItem
{
    private readonly System.Collections.Generic.Dictionary<int, ItemDef> _dataMap;
    private readonly System.Collections.Generic.List<ItemDef> _dataList;
    
    public TbItem(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, ItemDef>(count);
        _dataList = new System.Collections.Generic.List<ItemDef>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ItemDef _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.ItemDef.DeserializeItemDef(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemTypeId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ItemDef> DataMap => _dataMap;
    public System.Collections.Generic.List<ItemDef> DataList => _dataList;

    public ItemDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ItemDef Get(int key) => _dataMap[key];
    public ItemDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

