
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbMonster
{
    private readonly System.Collections.Generic.Dictionary<int, MonsterDef> _dataMap;
    private readonly System.Collections.Generic.List<MonsterDef> _dataList;
    
    public TbMonster(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, MonsterDef>(count);
        _dataList = new System.Collections.Generic.List<MonsterDef>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MonsterDef _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.MonsterDef.DeserializeMonsterDef(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.MonsterId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MonsterDef> DataMap => _dataMap;
    public System.Collections.Generic.List<MonsterDef> DataList => _dataList;

    public MonsterDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public MonsterDef Get(int key) => _dataMap[key];
    public MonsterDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

