
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 肉鸽小关
/// </summary>
public partial class TbRoguelikeLevel
{
    private readonly System.Collections.Generic.List<RoguelikeLevelDef> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), RoguelikeLevelDef> _dataMapUnion;

    public TbRoguelikeLevel(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<RoguelikeLevelDef>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            RoguelikeLevelDef _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.RoguelikeLevelDef.DeserializeRoguelikeLevelDef(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), RoguelikeLevelDef>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.BigLevelId, _v.LevelId), _v);
        }
    }

    public System.Collections.Generic.List<RoguelikeLevelDef> DataList => _dataList;

    public RoguelikeLevelDef Get(int BigLevelId, int LevelId) => _dataMapUnion.TryGetValue((BigLevelId, LevelId), out RoguelikeLevelDef __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

