
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 肉鸽效果
/// </summary>
public partial class TbRoguelikeEffect
{
    private readonly System.Collections.Generic.Dictionary<int, RoguelikeEffectDef> _dataMap;
    private readonly System.Collections.Generic.List<RoguelikeEffectDef> _dataList;
    
    public TbRoguelikeEffect(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, RoguelikeEffectDef>(count);
        _dataList = new System.Collections.Generic.List<RoguelikeEffectDef>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            RoguelikeEffectDef _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.RoguelikeEffectDef.DeserializeRoguelikeEffectDef(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.EffectId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RoguelikeEffectDef> DataMap => _dataMap;
    public System.Collections.Generic.List<RoguelikeEffectDef> DataList => _dataList;

    public RoguelikeEffectDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public RoguelikeEffectDef Get(int key) => _dataMap[key];
    public RoguelikeEffectDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

