
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 肉鸽商店道具
/// </summary>
public partial class TbRoguelikeItem
{
    private readonly System.Collections.Generic.Dictionary<int, RoguelikeItemDef> _dataMap;
    private readonly System.Collections.Generic.List<RoguelikeItemDef> _dataList;
    
    public TbRoguelikeItem(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, RoguelikeItemDef>(count);
        _dataList = new System.Collections.Generic.List<RoguelikeItemDef>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            RoguelikeItemDef _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.RoguelikeItemDef.DeserializeRoguelikeItemDef(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RoguelikeItemDef> DataMap => _dataMap;
    public System.Collections.Generic.List<RoguelikeItemDef> DataList => _dataList;

    public RoguelikeItemDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public RoguelikeItemDef Get(int key) => _dataMap[key];
    public RoguelikeItemDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

