
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbTower
{
    private readonly System.Collections.Generic.Dictionary<int, TowerDef> _dataMap;
    private readonly System.Collections.Generic.List<TowerDef> _dataList;
    
    public TbTower(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, TowerDef>(count);
        _dataList = new System.Collections.Generic.List<TowerDef>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TowerDef _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.TowerDef.DeserializeTowerDef(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.TowerId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TowerDef> DataMap => _dataMap;
    public System.Collections.Generic.List<TowerDef> DataList => _dataList;

    public TowerDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TowerDef Get(int key) => _dataMap[key];
    public TowerDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

