
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TowerDef : Luban.BeanBase
{
    public TowerDef(JSONNode _buf) 
    {
        { if(!_buf["TowerId"].IsNumber) { throw new SerializationException(); }  TowerId = _buf["TowerId"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Price1"].IsNumber) { throw new SerializationException(); }  Price1 = _buf["Price1"]; }
        { if(!_buf["Price2"].IsNumber) { throw new SerializationException(); }  Price2 = _buf["Price2"]; }
        { if(!_buf["Price3"].IsNumber) { throw new SerializationException(); }  Price3 = _buf["Price3"]; }
        { if(!_buf["AttackCd"].IsNumber) { throw new SerializationException(); }  AttackCd = _buf["AttackCd"]; }
        { if(!_buf["BodyRadius1"].IsNumber) { throw new SerializationException(); }  BodyRadius1 = _buf["BodyRadius1"]; }
        { if(!_buf["BodyRadius2"].IsNumber) { throw new SerializationException(); }  BodyRadius2 = _buf["BodyRadius2"]; }
        { if(!_buf["BodyRadius3"].IsNumber) { throw new SerializationException(); }  BodyRadius3 = _buf["BodyRadius3"]; }
        { if(!_buf["Scale"].IsNumber) { throw new SerializationException(); }  Scale = _buf["Scale"]; }
        { if(!_buf["MaxLevel"].IsNumber) { throw new SerializationException(); }  MaxLevel = _buf["MaxLevel"]; }
    }

    public static TowerDef DeserializeTowerDef(JSONNode _buf)
    {
        return new TowerDef(_buf);
    }

    /// <summary>
    /// 防御塔ID
    /// </summary>
    public readonly int TowerId;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 1级价格
    /// </summary>
    public readonly int Price1;
    /// <summary>
    /// 2级价格
    /// </summary>
    public readonly int Price2;
    /// <summary>
    /// 3级价格
    /// </summary>
    public readonly int Price3;
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public readonly float AttackCd;
    /// <summary>
    /// 1级范围
    /// </summary>
    public readonly float BodyRadius1;
    /// <summary>
    /// 2级范围
    /// </summary>
    public readonly float BodyRadius2;
    /// <summary>
    /// 3级范围
    /// </summary>
    public readonly float BodyRadius3;
    /// <summary>
    /// 缩放
    /// </summary>
    public readonly float Scale;
    /// <summary>
    /// 最大等级
    /// </summary>
    public readonly int MaxLevel;
   
    public const int __ID__ = -695517092;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TowerId:" + TowerId + ","
        + "Name:" + Name + ","
        + "Price1:" + Price1 + ","
        + "Price2:" + Price2 + ","
        + "Price3:" + Price3 + ","
        + "AttackCd:" + AttackCd + ","
        + "BodyRadius1:" + BodyRadius1 + ","
        + "BodyRadius2:" + BodyRadius2 + ","
        + "BodyRadius3:" + BodyRadius3 + ","
        + "Scale:" + Scale + ","
        + "MaxLevel:" + MaxLevel + ","
        + "}";
    }
}
}

